apiVersion: v1
kind: Service
metadata:
  name: slack-command-lb
  annotations:
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: slack-command
