apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: slack-command-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slack-command
  template:
    metadata:
      labels:
        app: slack-command
    spec:
      containers:
        - name: nginx-container
          image: "your docker images"
          ports:
            - containerPort: 80
        - name: flask-container
          image: "your docker images"
          env:
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: search-api-auth
                  key: SEARCH_API_KEY
            - name: ENGINE_ID
              valueFrom:
                secretKeyRef:
                  name: search-api-auth
                  key: ENGINE_ID
